# Generated by Django 3.1.1 on 2020-10-10 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200928_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank='True', default='default.jpg', null='True', upload_to='profile_pics/')),
                ('phone', models.CharField(blank='True', max_length=11, null='True')),
                ('hobbies', models.CharField(blank='True', max_length=300, null='True')),
                ('profession', models.CharField(blank='True', max_length=150, null='True')),
                ('quotes', models.CharField(blank='True', max_length=150, null='True')),
                ('user', models.OneToOneField(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
