# Generated by Django 3.1.1 on 2020-10-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201015_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(blank='True', default='default-blog-thumb.png', null='True', upload_to='blog_pics/'),
        ),
    ]
